version: '3'
services:
  auth-service:
    build: ./services/auth-service
    ports:
      - "3001:3001"
    env_file:
      - ./services/auth-service/.env

  user-service:
    build: ./services/user-service
    ports:
      - "3002:3002"
    env_file:
      - ./services/user-service/.env

  product-service:
    build: ./services/product-service
    ports:
      - "3003:3003"
    env_file:
      - ./services/product-service/.env

  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    env_file:
      - ./gateway/.env
    depends_on:
      - auth-service
      - user-service
      - product-service
